### ISSUE TITLE
[VisibleWhen] on Inline?

### ISSUE THREAD

**Issue by ajboni** [vexe/VFW#16]
It seems that VisibleWhen is ignore when a component is drawn inline.
![captura](https://cloud.githubusercontent.com/assets/12578313/7785993/96216f02-0185-11e5-983c-347b2864abd7.JPG)

**Comment by vexe** [comment]
Hello and thanks for using my humble tool!

It's not about Inline itself, it's just that VisibleWhen currently only works for members directly inside a BetterBehaviour/ScriptableObject, but not when they're drawn recursively (inside a SystemObject or say, list of scripts like you have)

Will be fixed in 1.3.2

**Comment by ajboni** [comment]
Thanks for the quick answer! This tools is incredible! its saving me a lot of headachesI had with cusom editors, drawers etc... I'm having a similar case with [Show], maybe related. I'll open another Issue to keep things tidy.
