### ISSUE TITLE
 Display(Dict.HorizontalPairs)] with class 

### ISSUE THREAD

**Issue by ajboni** [vexe/VFW#38]
Hello Vexe,

Is there any way to force the inline of a dictionary value (which is a class ) to render on a new line ? (instead of gui.horizontal)... 
I better explain it with pictures xD

```
        [Display(Dict.HorizontalPairs)]
        public Dictionary<int, Weapon> weapons;

        public class Weapon 
        {
            public string name;
            public float fireRate;
            public int clipSize;
        }
```

![2015-07-04 11_08_03-unity personal 64bit - vicraider unity - uae - web player_ _dx11_](https://cloud.githubusercontent.com/assets/12578313/8508188/0ecfe96a-223d-11e5-944d-f2ac9867f429.jpg)

If you make an instance and click the foldout you get this:  
![2015-07-04 11_17_22-unity personal 64bit - vicraider unity - uae - web player_ _dx11_](https://cloud.githubusercontent.com/assets/12578313/8508215/475ec778-223e-11e5-9d72-f8b24cdc5538.jpg)

It would be **really** nice if we could get something like this!:
![2015-07-04 11_25_26-unity personal 64bit - vicraider unity - uae - web player_ _dx11_](https://cloud.githubusercontent.com/assets/12578313/8508250/db38a95e-223f-11e5-941f-2a5a77ba172a.jpg)

Thanks!!

**Comment by vexe** [comment]
I think displaying the weapon data in its own block is easy, we just put it in a Vertical block. But It is tricky to always position the foldout arrow in the correct place. I'll give it a try.

**Comment by vexe** [comment]
It doesn't seem so trivial. The problem is that the whole key-value pair is in a single Horizontal block, so every Vertical block that comes after, will also be aligned horizontally (that's why you're seeing the Weapon fields in a Vertical block 'besides' it, not below it).

You could always drop the HorizontalPair (it is designed for simple key-value pairs)

This answer probably wasn't satisfying, and since you're a valuable customer I will give you a special treat :p

What you're trying to do can be accomplished in a much more elegant and powerful way. It will also give you a very nice inspector visual for your data.

The idea is very simple and powerful, you simply use a dictionary of string as key, and a struct as value. The struct wraps a float and a string. The idea is that this struct will represent the most-used and common data types in games, that is int, bool, float (represented by that float) and text (represented by the string field) - You then define operators to cast from/to those data types/ and that struct.

At the end, you will be able to say:

   var weapon = new Item();
   weapon["FireRate"] = 1f; 
   weapon["Name"] = "Berrta";
   weapon["ClipSize"] = 15;

(of course instead of using string literals you should use constants in a static class)

I hope you can see how powerful that is, you can basically add/remove data fields as you wish. The only way to do that in regular oop programming is if you use different classes to contain those data fields. But this way, you add and remove as you wish. Added bonus: With this approach, you don't need any version compatibility if you use a custom serializer, it's just a dictionary :)

This idea changed the way I think and write games, it drastically improved my progress, you can use it to build almost any system: FSM, BehaviourTrees, Puzzles, DialogueTrees, etc. Basically 'anything' that has 'properties'. This eliminates the need for oop altogether, say for ex a Zombie script, you have different zombies in your game, instead of creating new zombies by deriving from a base Zombie class, you just give your zombie that magical dictionary/data container and have each different type of zombie have different type of data (e.g. a zombie that spits acid might have a "AcidDamage" key/property/data, another that burns, might have "FireDamage" etc)

Another powerful benefit is that this way you could put your data in files, and construct them that way. This is what I do personally in my game. http://i.imgur.com/QMEa34j.png

Here's how the inspector looks: http://i.imgur.com/8uJOK2u.png

Here's a sample test project, (not using Vfw) https://copy.com/jFZf2rY6TLkRMRyy - you have an inventory class, with items. You read items from file and put them in this dictionary I told you about. You can represent pretty much ALL your game items, with a single Item class!

If you're interested about this approach I could send you the full version I'm using in my personal game, just pm me in forums.

Cheers!

**Comment by ajboni** [comment]
Wow! thats a really **REALLY** awesome Answer!!! 
About my example: I thought that after trying to add it myself and fail miserably (thats why I asked you ^^). 
What I was trying to achieve is to give the user visual feedback of all "tweets" the player received, categorized by "sender". So I have a dictionary of `<string, list<Tweet[ ]>>`   but is not that big deal honestly...

Then I saw your aproach and... just wow, honestly, the inventory scene sold me instantly! So much possibilities!
Im really interested in trying to implement this. I  also happen to have a lot of input that I want to "externalize" or to make the user able to externalize. (that tweets are an example) and im mporting form JSON  and mapping to a class that need to be defined, so I have the need to know about everything.

If im getting this right, this implementation would offer me the possibiliy to leave the data fields in hands of the user and handle "unknown" data!

I will try implement  something basic to test it (the tweets system sounds good)
Do you know Where I can read more about this approach, or its your idea?

Thank you!

**Comment by vexe** [comment]
Haha, I wish there was something official to read about it (cause then we'd have less crappy object-oriented garbage), but I couldn't find any - It's one of those 'secret-of-the-trade' things, where you only know about it if you get attached to some people in the game industry who really know their stuff (l33t). I happen to have the honor of working with an epic game designer Alexander Brazie who introduced me to the idea. I almost fell in tears after converting and looking at my items code... He said the credits doesn't go to him but Lua, it uses a similar concept with its 'table' structure.

And yes it's all about data, you can easily extern your stuff to files, no need for fancy complicated parsers or formats (JSON etc) - the format here is very simple.

```
HEADER
{
     KEY = VALUE,
     etc.
}
```

Here's the full implementation I use, with the drawers http://pastebin.com/JYZxj2nr

My Item class just inherits DataContainer, and specified getters/setters to quickly access the container data: http://i.imgur.com/vbxTF3t.png - 'k' is a static class that contains constants.

If you go with this approach, I strongly recommend you use BaseBehaviour instead of BetterBehaviour, cause FullSerializer is really not good when serializing dictionaries, let alone Items (arrays of dictionaries) - The DataContainer I sent you derives from SerializableDictionary, which works well with Unity's serialization system so no need for custom serialization it will just slow things down.

Cheers!

**Comment by ajboni** [comment]
Ah man, this is awesome! I'm really grateful! 
Lot of work to do now! thanks again!

**Comment by vexe** [comment]
If you go with this approach, you might deal with string concatenations, e.g. a weapon could have more than one fire rates stored as FireRate0 and FireRate1 - You'd like to get the value of a certain rate by an index, so you do float rate = weapon["FireRate" + index]; << which will allocate. Check out my gstring for GC free string operations http://forum.unity3d.com/threads/gstring-gc-free-string-for-unity.338588/

**Comment by ajboni** [comment]
Hey, I did try it yesterday with the help of your files "out of the box", and it was awesome!, so simple and powerfull. In conjuntion with serializable dictionary it's a beast! (though I had to ditch Horizontal Pairs xD)
https://www.youtube.com/watch?v=C3UbiB0caLU

About the strings, I thought about the exact same thing yesterday about indexes and mostly iterating through certain properties as they were a list. lets say you have:

```
person
{
Name = John
Age = 56
Height = 1,80
Address01 = 123 abc
Address02 = 456 zxc
Address03 = 789 asd
}
```

If you want to get a list of addresses (or iterate through them) you'll have to some manual work. 

I'm about to check your gstring video (volume is really low!), it seems really useful, thanks!!!

**Comment by vexe** [comment]
No need for HorizontalPairs cause it's applied dynamically in the Container drawer I sent. Using gstring + a custom struct enumerator, we could write a handy little enumerator for that (doesn't allocate)

I would imagine the usage would be something like:

```
foreach(var address in person.Iterate("Address")) // or .Enumerate or sth
       print(address);
```

Audio is a bit low yeah, might re-up it with higher volume.

**Comment by ajboni** [comment]
yup, I gave it a shot, not so good at coding so it could be much better, but it works. the thing that bothers is that you cant use int with starting zeroes (address01) and if you miss a consecutive number it will stop. but it kinda works. 
Also I was thinking in maybe returning a new DataContainer instead of a list, should be similar...

```
        public List<GameData> Enumerate(string baseAttribute, int startingIndex)
        {
            List<GameData> result = new List<GameData>();
            int index = startingIndex;
            string seqMember = baseAttribute;

            while (index >= startingIndex)
            {
                seqMember = baseAttribute + index.ToString();

                if (this.ContainsKey(seqMember))
                {
                    result.Add(this[seqMember]);
                    index += 1;
                }
                else
                {
                    index = -1;
                }
            }
            return result;
        }
```

and to call it simply 

```
 [Show] public void test(string key, string baseAttribute, int startingIndex)
        {   //Debug
            List<IOU.GameData> list = dataContainer.Enumerate(baseAttribute, startingIndex);
            foreach (IOU.GameData item in list)
            {
                print(item);
            }
        }
```

**Comment by vexe** [comment]
I was thinking of more like this (inside of DataContainer):

```
   ContainerEnumerator iter = new ContainerEnumerator();

    public ContainerEnumerator Iterate(string key)
    {
        iter.container = this;
        iter.key = key;
        return iter;
    }

    public class ContainerEnumerator : IEnumerator<GameData>
    {
        public DataContainer container;
        public string key;

        private int index;

        public ContainerEnumerator()
        {
            index = -1;
        }

        public ContainerEnumerator GetEnumerator()
        {
            return this;
        }

        public GameData Current
        {
            get
            {
                using(gstring.Block())
                    return container[gstring.Concat(key, index)];
                //return container[key + index]; //Allocation
            }
        }

        public bool MoveNext()
        {
            index++;
            using (gstring.Block())
                return container.ContainsKey(gstring.Concat(key, index));
            //return container.ContainsKey(key + index); //Allocation
        }

        object IEnumerator.Current
        {
            get { return Current; }
        }

        public void Reset()
        {
            index = -1;
        }

        public void Dispose()
        {
        }
    }
```

// Test.cs

```
DataContainer container = new DataContainer();

void OnEnable()
{
    for (int i = 0; i < 10; i++)
        container["Address" + i] = UnityEngine.Random.Range(i, 10);
}

void Update()
{
    Profiler.BeginSample("Container.Iterate");
    foreach(var address in container.Iterate("Address"))
    {
        int value = address;
    }
    Profiler.EndSample();
}
```

Allocates 0 bytes if the gstring version is used. :)

**Comment by ajboni** [comment]
Yup, that's so much better! ill add it!
Fyi, gstring crashes the VS compiler, though I admit I didn't try it that much... I'll try to give you feedback tomorrow.

Thanks!!

**Comment by vexe** [comment]
Try moving the gmcs/smcs files out and go directly under "Assets",
close/reopen Unity. Compiling to a dll will definitely solve all compile
issues, but I just wanted to share the code.

**Comment by ajboni** [comment]
Hey Vexe, Im still playing with this LUA-ish approach, and its been really great...
To better handle the lists, I can inherit from DataContainer and make a property which will return a new child DataContainer,  this gives us multiple levels of "Game Data"... This makes possible to have lists inside the datacontainer, and to structurize a little better the external file (if using any):

```
   [System.Serializable]
    public class Quest : IOU.DataContainer
    {
        private IOU.DataContainer requirements = new IOU.DataContainer();
        public IOU.DataContainer Requirements
        {
            get { return requirements; }
        }
    }
```

And then get it like you normally do (questList is a dictionary of Quests)

```
            questList.Add("Open the door", new Quest());
            questList["Open the door"]["State"] = "Not Started";
            questList["Open the door"]["Description"] = "I need to open the door";
            questList["Open the door"]["Found Key"] = false;
            questList["Open the door"]["Got Password"] = false;
            questList["Open the door"]["Quest 123"] = "finished";

            questList["Open the door"].Requirements["Found Key"] = true;
            questList["Open the door"].Requirements["Got Password"] = true;
            questList["Open the door"].Requirements["Quest 123"] = "finished";
```

It's working great, however i'm stuck in making the Editor Drawer show that "Requirements" Property in the inspector. The question is if this is even possible?

Thanks!!
Rodo.

**Comment by vexe** [comment]
This will look a bit weird in the inspector, but it works and can be adjusted to look properly

```
public class QuestDrawer : ObjectDrawer<Quest>
{
    IDictionaryDrawer<string, GameData> drawer;
    RecursiveDrawer recursive;

    protected override void Initialize()
    {
        var display = new DisplayAttribute(Dict.HorizontalPairs | Dict.Filter | Dict.ManualAlloc);
        var attr = member.Attributes.GetAttribute<DisplayAttribute>();
        if (attr  != null)
            EditorMember.CombineDisplays(src: attr, dest: display);

        drawer = new IDictionaryDrawer<string, GameData>();
        drawer.Initialize(member, new Attribute[] { qst_display }, gui);
        //drawer.UpdateCount = false;

        recursive = new RecursiveDrawer();
        recursive.Initialize(member, null, gui);
    }

    public override void OnGUI()
    {
        recursive.OnGUI();
        drawer.OnGUI();
    }
}
```

The idea is to use a RecursiveDrawer inside of QuestDrawer to draw whatever stuff you throw inside of it.

Remember to: Register/map this drawer - Go to SerializableDictionary and mark all the fields with HideInInspector - Go to Quest and mark requirements with Show.

**Comment by ajboni** [comment]
ah!! You are the man! Thank mate, I promise not to bother anymore haha

**Comment by vexe** [comment]
if I were you I'd probably look for a way to store the requirements in the quest container itself: either like this:

quest["req_found key"] = true; // again, using gstring you could enumerate the requirements without allocation

or

quest["req0"] = "found key";

to mark a requirement as 'finished' - you just remove it from the quest container. quest.Remove("req0");

**Comment by ajboni** [comment]
Yup i know what you mean, to keep it simple... I'm playing with it... I dont quite like the idea of using prefixes...

Tried making the Quest class do not be a dataCointaner but having two dataContainer properties: Requirements and Properties.
so I would parse a File with a "subheader" to identify conditions (or anything)

```
Get the Cereal
{
  [Properties]
  Description = I'm starving I need to open the pod and get the cereal.
  State = Hidden
  OtherProperty = 0

  [Requirements]
  hasCereal = true;
  hasBowl = true;
  unlockedDoor = true;
  magicNumber = 10;
}
```

Then on runtime I could use your suggestion of removing the requirements, enumerate them and finding when they are done...
Again, the flexibility this aproach gives you is incredible°!

**Comment by vexe** [comment]
Right - this seems a proper place for a composition relation. a quest
having two containers makes more sense than the previous setup.

**Comment by vexe** [comment]
Turns out also Jon Blow uses records everywhere too =))) 18:15 https://www.youtube.com/watch?v=JjDsP5n2kSM

**Comment by ajboni** [comment]
Nice!! And good talk...  
You should extend you implementation and make a Framework! :D or make it available in VFW !!

**Comment by gresolio** [comment]
Recently I started to write some custom Editor scripts (Property Drawers and Custom Inspectors) for my current project. I faced the GUILayout issues with Property Drawers, exactly like in this [answer](http://forum.unity3d.com/threads/inspector-custom-propertydrawers-dont-support-beginscrollview.199628/) :) After that I found your ['hacky' solution](http://answers.unity3d.com/questions/661360/finally-a-solution-cant-use-guilayout-stuff-in-pro.html) and VFW. I really liked "[Why did you take out the custom serialization features](http://forum.unity3d.com/threads/open-source-vfw-134-drawers-save-system-serialize-interfaces-generics-autoprops-delegates.266165/page-9#post-2478086)". Then reading about [gstring](http://forum.unity3d.com/threads/gstring-gc-free-string-for-unity.338588/#post-2191184) and finally I am here )))

> Here's a sample test project, (not using Vfw) https://copy.com/jFZf2rY6TLkRMRyy - you have an inventory class, with items. You read items from file and put them in this dictionary I told you about. You can represent pretty much ALL your game items, with a single Item class!

Can you please re-upload a sample test project (share via Google Drive for example), because it looks like a dead link (error code: 1084 Maintenence). It would be nice to see this example. Thanks in advance

p.s. The strange chain of events for me... From Editor scripting to Unity serialization issues, and "a better workflow, a better approach to storing your data" :)
