### ISSUE TITLE
Serialization error with a compiled build, but not in Unity Editor

### ISSUE THREAD

**Issue by geff** [vexe/VFW#44]
VFW works fine (thanks Vexe) in Unity Editor but when I launch the compiled version of my game i've got this error in output_log.txt  :

_**A script behaviour has a different serialization layout when loading. (Read 40 bytes but expected 268 bytes)
Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?**_

I'm working with Unity 5.1.1p4 and the last version of VFW Package (vfw133p2)

I use some polymorphism :

``` c#
public class HeroAbilityData : BetterScriptableObject
{
    public string Name;
    public Sprite Icon;
    public int Level = 1;
    public int GaugeAttackConsumption = 10;

    public HeroAbility Ability;
}

[CreateAssetMenu(menuName = "Hero Abilities/Rush")]
public class HeroAbilityData_Rush : HeroAbilityData
{
    public HeroAbilityData_Rush()
    {
        this.Ability = new Rush(); // <-- Polymorphism, that's why I use VFW
    }
}

[Serializable]
public class HeroAbility
{
    public virtual void Init()
    {

    }

    public virtual void Use()
    {

    }
}

[Serializable]
public class Rush : HeroAbility
{
}
```

@vexe do you have some ideas, solutions ?

Thanks,
# geff

**Comment by vexe** [comment]
What platform are you targeting? What have you tried to diagnose the problem? Basic divide and conquer should give you some answers. Take out the HeroAbility field from from HeroAbilityData. Does it make any difference? Try messing around a bit more, remove/add bits and pieces till you find the problem source. If you did, let me know. If you didn't, send me a copy of the project so I take a look.

**Comment by geff** [comment]
Hi vexe,

I solved my problem by simplifying it.
My previous code was for a Unity World without support of polymorphism, but thanks to VFW I can delete a part of this code.

I don't need the intermediate Scriptable Object _HeroAbilityData_Rush_. Instead of creating a specific asset for each ability, I create a HeroAbilityAsset and drag'n drop my hability code.

Thanks for creating VFW, Unity seems more developer friendly and less frustrating with it.

VFW Serializer do not support this type of polymorphism in constructor :

``` c#
this.Ability = new Rush();
```

My new code :

``` c#
[CreateAssetMenu(menuName = "Hero Ability")]
public class HeroAbilityData : BetterScriptableObject
{
    public string Name;
    public Sprite Icon;
    public int Level = 1;
    public int GaugeAttackConsumption = 10;

    public HeroAbility Ability;
}

[Serializable]
public abstract class HeroAbility
{
    public abstract void Init();

    public abstract void Use();
}

[Serializable]
public class Rush : HeroAbility
{
    public override void Init()
    {
    }

    public override void Use()
    {
    }
}
```

**Comment by vexe** [comment]
Right. You shouldn't use constructors with Unity's objects (MonoBehaviour/ScriptableObjects) - the resulting behavior is not very deterministic.

That said, I should mention this: I became a game developer for one reason, which is to develop this one very specific game. All the tools I write serve the development of this game. I came from a non-game dev background. I thought most the standards/principles I applied on previous software I wrote are applicable to game dev as well. Since I had no game experience at the time, I looked at the state of Unity's editor and its weak serialization, I went oh man this is pretty bad! How can they not support this and that, they're important! - I started 'assuming' that 'this and that' are important (based on previous non game dev knowledge) - So I went ahead and added custom serialization to fill in the gaps, I was happy! 

At that time I still haven't yet gotten my hands 'very' dirty in game programming. As I did, I noticed that the requirements and standards are 'vastly' different than what you'd need/do in normal software dev. I ended up not using most the things I 'assumed' I'd be needing/using, one of those things is 'polymorphic serialization' - I started listening to talks from Jon Blow, Mike Acton, John Carmack and the like about the way they write games... and oh boy is it different from the way we assume how it should be. Those talks made me more open-minded and not so rigid (obeying OOP principles like it's a religion of some sort) - I looked at things like data-oriented development, locality of reference, cache friendliness, etc and how OOP is very harmful in many situations. I looked at data driven designs and many other alternative game dev approaches how to structure your data in a better way. Then I met this awesome ex-blizzard game designer who introduced me to the idea of 'data/property containers', since then I never looked back! I gave some pointers about it here http://forum.unity3d.com/threads/gstring-gc-free-string-for-unity.338588/ (my long post at the end) and here https://github.com/vexe/VFW/issues/38

I highly recommend that you look into those approaches. I'm not dictating how you should program, I'm merely saying "hey, I used to use the same techniques you're using in my games, they didn't work out so well for me. I found this cool alternative technique, worked out pretty well, check it out!"

What I learned from my little experience is that simplicity is what matters most, cause it almost always implies robustness and thus less buggy code, thus more programmer happiness (less frustration, more productivity). OOP encourages complexity, by driving our attention and focus away from the real problem (data) into some very high abstractions that exist in a fairy land (objects) - Games are big software, composed of many systems and sub-systems to those systems. If every sub-system of the game was complex, sophisticated, riddled with all these redundant abstractions, what do you think that output of combining all those systems to build the game would be?

All that said I think OOP is fine for framework and editor codes - it gives users flexibility that in the most case they care about having. Also when inheriting from your base script (Mono/Better/Base Behaviour).. Other than that (gameplay codes) I believe it's completely obsolete (Item system: multiple item types, enemies: different enemy types, AI: different behaviours etc all of those could be implemented in much more superior ways)

Imho we shouldn't let anybody confine our thoughts in a box of their making, we should be free, think out of the box, if someone tells me approach A is good, and B is bad, I will experience and try both of them, and judge for myself!

Cheers!

**Comment by geff** [comment]
You're right, traditional OOP is evil, especilly in component based engine.

Even in traditional development I prefer using Interface instead of inheritance.

But there is something that is sacred for me : Strongly typed code
I prefer using Enum than string and a minimum of class abstraction when needed.

Thanks for your advice and for VFW which should be a part of Unity.

#geff

**Comment by vexe** [comment]
Correct, enums are very powerful (and underrated)

Dealing with string literals is very error-prone. Take tags for instance, if (other.CompareTag("player")) <-- oops, typo. meant "Player" - But this could easily be addressed with a static class and some constants.

public static class Tags { public const string Player = "Player" }

I only used string literals in the examples in the links for demonstration, I have most my important string keys as constants defined in static classes.

You could definitely use enums as keys for your containers (very good optimization), but since I'm in a pre-production chaotic state, I like the ability to add/remove keys on the fly without having to pre-define them.
