### ISSUE TITLE
Regarding Editor Windows and GUI

### ISSUE THREAD

**Issue by Igneom** [vexe/VFW#51]
I was creating an editor window using BetterWindow, since using unity's way is almost a nightmare, and I needed a scrollable area to display buttons in a hierarchical way, I noticed that there's a ScrollView property on the gui, so I decided to try and use it, but then as soon as I implemented a simple example of it, I noticed that it isn't finished like the horizontal and vertical blocks, the class exists but there's no derived class to implement it's abstract End/BeginScrollView, or i'm trying to use it wrong, While doing the editor window I also noticed that Layout.sExpandWidth/Height is not implemented as well.

Anyway, the point is, how much suitable is the improved GUI to do an Editor Window without resorting now and then to the unity GUI, what is your recommendation (if any), and what are your plans to keep implementing the GUI?

**Comment by vexe** [comment]
Hi there,

yeah Scroll views are not implemented yet for RabbitGUI because they rely on the implementation of ExpandWidth/Height which are also not implemented like you said. I haven't put serious effort into it, I imagine it's a bit tedious but doable.

Depending on what you're doing, you could try a couple of things, one don't use a scrollview but use pages/tabs where you have a list of things you want to display and next/previous buttons to cycle pages, this picture should explain it better:http://i.imgur.com/iXbzDNH.png

Since you mentioned you're dealing with hierarchies, that might not be a feasible approach. Your only option now is to use TurtleGUI which shares the same API with RabbitGUI. It has ScrollView implemented but some of the last gui controls I added are not. Just check TurtleGUI.cs search for NotImplementedException and cycle finds to see what's up.

**Comment by Igneom** [comment]
Ended up using the default unity EditorWindow, even though it's a mess, but I still don't understand completely how the internals of vfw work yet, enough for me to implement the missing features I needed.

But still, while trying ways around it to replicate something similar, and for other reasons as well, I noticed that on the ObjectDrawer, Initialize sometimes is called after OnGUI. From my understanding, Initialize is used to check for null values, and initialize certain other values on the drawer, and if the object has previously serialized values, load them after the initialize and before the OnGUI, but that is not the case on certain times, creating several errors on the OnGUI method, which forces me to test for various possible cases inside the OnGUI to assure the value is correct.

I don't know yet if it's a bug or I'm misusing it, but your comments on the intentions of the Initialize method and when it's called exactly would give a very good insight on this.

**Comment by vexe** [comment]
It's all in BaseGUI/Controls/Members.cs Initialize is called before OnGUI. It's like you said it's used to initialize values and such. But the thing is, depending on your drawer, you can't rely on it solely because it gets called only once. So if you have something in your OnGUI that the user could set to null you should check for null inside OnGUI in that case.  See SequenceDrawer.cs for example, I check if the array/list value is null, if so I instantiate a new one. You must do this in a place where it gets called multiple times before the value is used, otherwise if the user sets the array/list value to null somehow, you'd get null exceptions. Makes sense?

**Comment by Igneom** [comment]
It does, I thought at first they worked similar to OnEnable, but they are more like Awake, thanks for the clarification.
