### ISSUE TITLE
FullSerializer delegate/Action/Func

### ISSUE THREAD

**Issue by krisrok** [vexe/VFW#59]
i just realized this behaviour is really an issue of FullSerializer and not VWF's, but maybe you have an idea how to solve this.

i really like the BetterBehaviour editor drawer goodness. but in this particular case it fails. let me outline it for you:

``` c#
public class MyComponent : BetterBehaviour
{
  public MyComputer Computer = new MyComputer{ Compute = (a,b) => a + b };

  public void Update()
  {
    Debug.Log(Computer.Compute(1,2)); // will throw NullPointerException
  }
}

public class MyComputer
{
  public Func<float, float, float> Compute;
  public string SomeValueIWantToSeeInInspector = "abc";
}
```

this will throw a NullPointerException as the Compute-Func does not get serialized correctly. if i switch to MonoBehaviour it works but it misses the inspector features.

note: i want to be able to inspect other parts of the Computer object, i do NOT want to see/modify the Func<>.

**Comment by vexe** [comment]
Funcs/Actions are not serialized directly. Read the docs. You should use uFunc/uAction instead. And not just that, anonymous methods and lamdas are not serialized, only regular methods inside objects are. - You could use Unity's events too if you like.

Although it sounds very handy to serialize delegates, but in my experience there is very little practical benefit in doing so. You can in almost all cases just wire up the delegate in Awake/OnEnable and not have it serialized, it's not worth the complexity. This is because, if you use inspectable delegates than you're relying on the inspector to set things up for you, I used to believe this was a great idea, but the more I programmed my game I realized otherwise. It's a bad idea to fully trust Unity's or any form of custom serialization (because it also relies on Unity's at its core) because it could easily break, scenes could get easily corrupted and you lose hours and hours of effort connecting your delegates in the editor, at that point you're screwed. This happened to me countless times, especially if I leave my project for a while, get back to it in a later Unity version.

**Comment by vexe** [comment]
I think you're getting the exception (Btw it's NullReferenceException not NullPointerException) because you're using the field initializer on a non-serializable-by-Unity class/field. Try doing the initialization in Awake, or just mark MyComputer with [Serializable] and let MyComponent inherit BaseBehaviour instead of BetterBehaviour since you're not using any custom serialization. (This has nothing to do with delegates)

i.e.

```
public class MyComponent : BetterBehaviour
{
  public MyComputer Computer;

  void Awake() {  Computer = new MyComputer{ Compute = (a,b) => a + b }; }

  void Update()
  {
    Debug.Log(Computer.Compute(1,2)); // will throw NullPointerException
  }    
}
```

Or

```
public class MyComponent : BaseBehaviour
{
  public MyComputer Computer = new MyComputer{ Compute = (a,b) => a + b };

  void Update()
  {
    Debug.Log(Computer.Compute(1,2)); // will throw NullPointerException
  }    
}

[Serializable]
public class MyComputer { ... }
```

**Comment by krisrok** [comment]
hey thanks for your swift reply.

i want to be able to inspect (read-only would do fine) other properties of the MyComputer thing. it was just a lean example :)

in the real world use case it looks like this: Component->CustomProperty->CustomPropertySettings->Func

i also noticed it is fine without the field initializer, i guess this has to do.

the uFunc stuff i didn't quite get. could you modify my example code above to work with a uFunc instead?

**Comment by vexe** [comment]
Your particular example won't work cause you're assigning 'Compute' to an anonymous function, you would have to do:

```
public class MyComponent : BaseBehaviour
{
      public MyComputer Computer;

      void Awake() {  Computer = new MyComputer{ Compute = ComputeFn }; }

      public void Update()
      {
            Debug.Log(Computer.Compute(1,2));
      }

      public float ComputeFn(float f0, float f1) { return f0 + f1; }
}

[Serializable] public class MyComputer
{
      [Show] public uFunc<float, float, float> Compute;
      public string SomeValueIWantToSeeInInspector = "abc";
}
```

Note this is a BaseBehaviour approach, so 'Compute' is just an exposed/inspectable but _not_ serializable delegate. In VFW (not VWF :p) you can expose/show things even if they weren't serializable by explicitly marking them with [Show].

**Comment by krisrok** [comment]
heh, that's what i tried. but i cannot assign the method to uFunc, or to cite the compiler:

> Cannot convert method group 'ComputeDuration' to non-delegate type 'Vexe.Runtime.Types.uFunc<float,float,float>'. Did you intend to invoke the method?    

thanks for pointing out the Base-/BetterBehaviour difference. and for correcting NullReferenceException and the library name.. not my day ;)

**Comment by vexe** [comment]
Apologies, my mistake. It should be:

```
Computer = new MyComputer();
Computer.Compute = new uFunc<float, float, float>();
Computer.Compute.Add(ComputeFn);
```

You need to allocate a uFunc and use its Add method to add a handler.

**Comment by krisrok** [comment]
i see, now it works
