### ISSUE TITLE
OnChanged not working on calls from outside of class

### ISSUE THREAD

**Issue by Feldruebe** [vexe/VFW#80]
I have a property that is set from outside of the class.
The OnChanged function is only called if i set it from within the class.

Is this intended or a bug?

**Comment by vexe** [comment]
Are you changing the property value from code? OnChanged should be called only when you modify the field/property in the editor, and not from code.

**Comment by Feldruebe** [comment]
I am wondering

this triggers OnChanged when i hit space.

```
 public class OnChangedExample : BetterBehaviour
    {
        // when this string changes, set the `tag` property to the new value and log it
        [OnChanged("Log2")] // could have also written OnChanged("Log", Set = "tag")
        public string playerTag;

        public void Update()
        {
            if (Input.GetKeyUp(KeyCode.Space))
            {
                playerTag = "Player";
            }
        }

        public void Log2(string tag)
        {
            Log(tag);
        }
    }
```

**Comment by vexe** [comment]
That's because you probably have the editor/inspector selected for this gameObject so the drawer is active. If you look at the source code for the drawer it's checking to see if the value changed in its OnGUI. So yeah if you modify it from code while the drawer is active it still calls the OnChanged function.

This is probably one of those attributes that I would like to deprecate/get out of the core framework somehow. Because it's misleading in a way. To handle it properly I would have to do something similar to what I did with the Requirements attributes, i.e. have a piece of code that always runs and checks for anything that has OnChanged on it that way it works independent of whether the drawer is active or not.

**Comment by Feldruebe** [comment]
Ah ok.

Thanks for the respons.
