### ISSUE TITLE
 The type or namespace name `ItemPair`2' could not be found.

### ISSUE THREAD

**Issue by pointcache** [vexe/VFW#82]
Assets/Plugins/Vexe/Runtime/Libs/Helpers/ReflectionHelper.cs(55,30): error CS0246: The type or namespace name `ItemPair`2' could not be found. Are you missing a using directive or an assembly reference?

**Comment by vexe** [comment]
I renamed Tuple to ItemPair because it was causing issues in some platforms because they already have System.Tuple. Seems git didn't catch that rename or something. Downloading the Zip does yield the error. I'm on it.

**Comment by pointcache** [comment]
thanks for quick reply, could you also write down upgrade instructions? since you deprecated a whole lot on which my systems hold

**Comment by vexe** [comment]
It's more a downgrade at this stage. If your code relies on previous stuff, you could still use them (they're still there, not removed) - or you could stick to 1.3.4 in your current project (which is quite stable to be honest).

This is the thing about API design, you come up with an idea that you think is cool at the time of writing, you encourage people to use it, but then you find out you're totally wrong, and you were encouraging bad habits all along. But at that point it could be too late to undo the damage. I'd rather hit one down/up grade road bump rather than leaving users with code that I know is bad and will cause them tons of headaches in the future.

**Comment by pointcache** [comment]
So you actually removed BEtterBehavs with all the attributes? Like all of it or there is a substitution?

**Comment by vexe** [comment]
Just look at the "VFW Deprecated" folder, everything I deprecated is there. It's just BetterBehaviour and all the other serialization nonsense ([Serialize], [DontSerialize], etc), as well as delegates. The majority/rest of the drawers/attributes are all intact.

**Comment by vexe** [comment]
Could you try that again? https://github.com/vexe/VFW/commit/fec08aa859b08360d30970fe9d87faf8e0d6d6f3

**Comment by pointcache** [comment]
Done! Tested, works, thank you.

**Comment by vexe** [comment]
Awesome! Let me know if you have any more issues down the line.

Don't know if you noticed, but I just sneaked in another commit. You might have already got it but just in case, it was something I overlooked to rename.

**Comment by pointcache** [comment]
@vexe  hey man could you give me 10 mins on skype i want to show you something, add me if you want 
antonov.3d

**Comment by vexe** [comment]
Could you perhaps write me in email or send me screenshots? or is it not possible?

**Comment by pointcache** [comment]
nah it would take too long, just wanted to share screen to show what i did with your framework thats all

**Comment by vexe** [comment]
OK Sure.
